rx = comm.SDRuReceiver(...
    'Platform','B200', ...
    'SerialNum','31FD9D5', ...
    'CenterFrequency',2.45e9, ...
    'MasterClockRate',56e6, ...
    'DecimationFactor',256);

for frame = 1:2000
    data = rx();
    OFDM_receiver
      
end
release(rx)